/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native ground-truth generator for src/tests/wasm/test_pcoa_wasm.cpp.
 *
 * Computes PCoA on FIXTURE_UNWEIGHTED_DIST via skbb's libskbb.so
 * directly. The WASM test calls the same kernel via libskbb_wasm.a;
 * the comparison is numeric agreement between native skbb and WASM
 * skbb. Build & run via the wasm_regen_pcoa_expected Makefile target;
 * output goes to src/tests/wasm/expected/pcoa_expected.h.
 */

#define UNIFRAC_WASM_FIXTURES_USE_SKBB_SEED 1
#include "tests/wasm/fixtures.hpp"

#include <cstdint>
#include <scikit-bio-binaries/ordination.h>

int main(void) {
    constexpr uint32_t SEED = 42;
    constexpr unsigned int K = 3;
    const unsigned int N = FIXTURE_N_SAMP;

    su_compatible_seed(SEED);

    double eigenvalues[K]              = {0};
    double samples[K * 6]              = {0};   // K * FIXTURE_N_SAMP
    double proportion_explained[K]     = {0};

    skbb_pcoa_fsvd_fp64(N, FIXTURE_UNWEIGHTED_DIST, K, -1,
                        eigenvalues, samples, proportion_explained);

    std::printf("/* AUTO-GENERATED by src/tests/wasm/generate_pcoa_expected.cpp.\n");
    std::printf(" * Do not hand-edit. Run `make wasm_regen_pcoa_expected` to refresh.\n");
    std::printf(" *\n");
    std::printf(" * Input: FIXTURE_UNWEIGHTED_DIST (test/capi_inmem_test.c:99-104).\n");
    std::printf(" * Seed: %u; n_eighs=%u; produced via skbb_pcoa_fsvd_fp64\n", SEED, K);
    std::printf(" * with su::set_random_seed-compatible seed transform.\n");
    std::printf(" */\n\n");
    std::printf("#ifndef UNIFRAC_WASM_PCOA_EXPECTED_H\n");
    std::printf("#define UNIFRAC_WASM_PCOA_EXPECTED_H\n\n");
    std::printf("static const unsigned int PCOA_EXPECTED_N      = %u;  /* n_samples */\n", N);
    std::printf("static const unsigned int PCOA_EXPECTED_K      = %u;  /* n_dims    */\n", K);
    std::printf("static const unsigned int PCOA_EXPECTED_SEED   = %u;\n\n", SEED);
    emit_array_double("PCOA_EXPECTED_EIGENVALUES",          eigenvalues,          K);
    emit_array_double("PCOA_EXPECTED_SAMPLES",              samples,              K * N);
    emit_array_double("PCOA_EXPECTED_PROPORTION_EXPLAINED", proportion_explained, K);
    std::printf("#endif /* UNIFRAC_WASM_PCOA_EXPECTED_H */\n");

    return 0;
}
