/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native ground-truth generator for
 * src/tests/wasm/test_permanova_wasm.cpp.
 *
 * Build & run via the wasm_regen_permanova_expected Makefile target.
 */

#define UNIFRAC_WASM_FIXTURES_USE_SKBB_SEED 1
#include "tests/wasm/fixtures.hpp"

#include <cstdint>
#include <scikit-bio-binaries/distance.h>

int main(void) {
    constexpr uint32_t SEED        = 42;
    constexpr unsigned int N_PERM  = 999;
    const unsigned int N           = FIXTURE_N_SAMP;

    su_compatible_seed(SEED);

    double fstat = 0.0, pvalue = 0.0;
    skbb_permanova_fp64(N, FIXTURE_UNWEIGHTED_DIST, FIXTURE_GROUPING,
                        N_PERM, -1, &fstat, &pvalue);

    std::printf("/* AUTO-GENERATED by src/tests/wasm/generate_permanova_expected.cpp.\n");
    std::printf(" * Do not hand-edit. Run `make wasm_regen_permanova_expected` to refresh.\n");
    std::printf(" *\n");
    std::printf(" * Input: FIXTURE_UNWEIGHTED_DIST + FIXTURE_GROUPING.\n");
    std::printf(" * n_perm=%u; seed=%u; via skbb_permanova_fp64 with the\n", N_PERM, SEED);
    std::printf(" * su::set_random_seed-compatible seed transform.\n");
    std::printf(" */\n\n");
    std::printf("#ifndef UNIFRAC_WASM_PERMANOVA_EXPECTED_H\n");
    std::printf("#define UNIFRAC_WASM_PERMANOVA_EXPECTED_H\n\n");
    std::printf("static const unsigned int PERMANOVA_EXPECTED_N      = %u;\n", N);
    std::printf("static const unsigned int PERMANOVA_EXPECTED_N_PERM = %u;\n", N_PERM);
    std::printf("static const unsigned int PERMANOVA_EXPECTED_SEED   = %u;\n\n", SEED);
    std::printf("static const double PERMANOVA_EXPECTED_FSTAT  = %a;\n", fstat);
    std::printf("static const double PERMANOVA_EXPECTED_PVALUE = %a;\n\n", pvalue);
    std::printf("#endif /* UNIFRAC_WASM_PERMANOVA_EXPECTED_H */\n");

    return 0;
}
