/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native ground-truth generator for src/tests/wasm/test_permanova_wasm.cpp.
 *
 * Computes PERMANOVA on a fixed 6x6 distance matrix + grouping vector
 * via skbb's libskbb.so directly. The WASM test calls the same kernel
 * via libskbb_wasm.a; assertion is bit-exact equality (==), made
 * possible by skbb's portable Fisher-Yates shuffle (skbb commit 14b5306).
 *
 * Build & run via the wasm_regen_permanova_expected Makefile target.
 *
 * Replicates su::set_random_seed's seed transform so the seed seen by
 * skbb matches what ssu_set_random_seed produces under WASM.
 */

#include <cstdio>
#include <cstdint>
#include <random>

#include <scikit-bio-binaries/util.h>
#include <scikit-bio-binaries/distance.h>

// Same 6x6 unweighted-UniFrac distance matrix used by Stage 5.
static const unsigned int N = 6;
static const double DIST[N * N] = {
    0.0,         0.2,         0.57142857,  0.6,         0.5,         0.2,
    0.2,         0.0,         0.42857143,  0.66666667,  0.6,         0.33333333,
    0.57142857,  0.42857143,  0.0,         0.71428571,  0.85714286,  0.42857143,
    0.6,         0.66666667,  0.71428571,  0.0,         0.33333333,  0.4,
    0.5,         0.6,         0.85714286,  0.33333333,  0.0,         0.6,
    0.2,         0.33333333,  0.42857143,  0.4,         0.6,         0.0
};

// 2-group split: {0,1,5} vs {2,3,4}. Arbitrary but fixed.
static const unsigned int GROUPING[N] = {0, 0, 1, 1, 1, 0};
static const unsigned int N_PERM = 999;

static void su_compatible_seed(uint32_t s) {
    std::mt19937 g(s);
    uint32_t skbb_seed = g();
    skbb_set_random_seed(skbb_seed);
}

int main(void) {
    constexpr uint32_t SEED = 42;

    su_compatible_seed(SEED);

    double fstat = 0.0, pvalue = 0.0;
    skbb_permanova_fp64(N, DIST, GROUPING, N_PERM, -1, &fstat, &pvalue);

    std::printf("/* AUTO-GENERATED by src/tests/wasm/generate_permanova_expected.cpp.\n");
    std::printf(" * Do not hand-edit. Run `make wasm_regen_permanova_expected` to refresh.\n");
    std::printf(" *\n");
    std::printf(" * Input: 6x6 unweighted-UniFrac distance matrix from\n");
    std::printf(" *   test/capi_inmem_test.c:99-104 (native-CI-validated).\n");
    std::printf(" * Grouping: {0,0,1,1,1,0}; n_perm=%u; seed=%u\n", N_PERM, SEED);
    std::printf(" * Produced via skbb_permanova_fp64 with the\n");
    std::printf(" * su::set_random_seed-compatible seed transform.\n");
    std::printf(" */\n\n");
    std::printf("#ifndef UNIFRAC_WASM_PERMANOVA_EXPECTED_H\n");
    std::printf("#define UNIFRAC_WASM_PERMANOVA_EXPECTED_H\n\n");
    std::printf("static const unsigned int PERMANOVA_EXPECTED_N      = %u;\n", N);
    std::printf("static const unsigned int PERMANOVA_EXPECTED_N_PERM = %u;\n", N_PERM);
    std::printf("static const unsigned int PERMANOVA_EXPECTED_SEED   = %u;\n\n", SEED);
    std::printf("static const double PERMANOVA_EXPECTED_FSTAT  = %a;\n", fstat);
    std::printf("static const double PERMANOVA_EXPECTED_PVALUE = %a;\n\n", pvalue);
    std::printf("#endif /* UNIFRAC_WASM_PERMANOVA_EXPECTED_H */\n");

    return 0;
}
