/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native ground-truth generator for src/tests/wasm/test_pcoa_wasm.cpp.
 *
 * Computes PCoA on the 6x6 unweighted UniFrac distance matrix that
 * test/capi_inmem_test.c:99-104 already validates against the native
 * unifrac compute kernel, using skbb's libskbb.so directly. The WASM
 * test calls the same kernel via libssu_wasm.a -> libskbb_wasm.a; the
 * comparison is numeric agreement between native skbb and WASM skbb.
 *
 * Build & run via the wasm_regen_pcoa_expected Makefile target. Output
 * goes to src/tests/wasm/expected/pcoa_expected.h.
 *
 * IMPORTANT: this generator must replicate su::set_random_seed's seed
 * derivation byte-for-byte so the seed seen by skbb matches what
 * ssu_set_random_seed produces under WASM. su::set_random_seed seeds a
 * std::mt19937, draws one uint32, and passes that to skbb_set_random_seed;
 * we mirror that here.
 */

#include <cstdio>
#include <cstdint>
#include <random>

#include <scikit-bio-binaries/util.h>
#include <scikit-bio-binaries/ordination.h>

// 6x6 unweighted UniFrac distance matrix from test/capi_inmem_test.c:99-104.
// Row-major, symmetric, zero diagonal. Native CI validates these values.
static const unsigned int N = 6;
static const double DIST[N * N] = {
    0.0,         0.2,         0.57142857,  0.6,         0.5,         0.2,
    0.2,         0.0,         0.42857143,  0.66666667,  0.6,         0.33333333,
    0.57142857,  0.42857143,  0.0,         0.71428571,  0.85714286,  0.42857143,
    0.6,         0.66666667,  0.71428571,  0.0,         0.33333333,  0.4,
    0.5,         0.6,         0.85714286,  0.33333333,  0.0,         0.6,
    0.2,         0.33333333,  0.42857143,  0.4,         0.6,         0.0
};

// Match su::set_random_seed: seed mt19937 with `s`, draw one uint32, pass
// that to skbb_set_random_seed. The WASM test goes through ssu_set_random_seed
// which executes this exact sequence.
static void su_compatible_seed(uint32_t s) {
    std::mt19937 g(s);
    uint32_t skbb_seed = g();
    skbb_set_random_seed(skbb_seed);
}

static void emit_array_double(const char* name, const double* arr, unsigned int n) {
    std::printf("static const double %s[%u] = {\n", name, n);
    for (unsigned int i = 0; i < n; i++) {
        std::printf("    %a%s\n", arr[i], (i + 1 == n) ? "" : ",");
    }
    std::printf("};\n\n");
}

int main(void) {
    constexpr uint32_t SEED   = 42;
    constexpr unsigned int K  = 3;          // n_eighs / n_dims

    su_compatible_seed(SEED);

    double eigenvalues[K]              = {0};
    double samples[K * N]              = {0};
    double proportion_explained[K]     = {0};

    // Match su::pcoa(): seed=-1 lets skbb pull from its mt19937 (which we
    // just set via skbb_set_random_seed).
    skbb_pcoa_fsvd_fp64(N, DIST, K, -1, eigenvalues, samples, proportion_explained);

    std::printf("/* AUTO-GENERATED by src/tests/wasm/generate_pcoa_expected.cpp.\n");
    std::printf(" * Do not hand-edit. Run `make wasm_regen_pcoa_expected` to refresh.\n");
    std::printf(" *\n");
    std::printf(" * Input: 6x6 unweighted-UniFrac distance matrix from\n");
    std::printf(" *   test/capi_inmem_test.c:99-104 (native-CI-validated).\n");
    std::printf(" * Seed: %u; n_eighs=%u; produced via skbb_pcoa_fsvd_fp64\n", SEED, K);
    std::printf(" * with su::set_random_seed-compatible seed transform.\n");
    std::printf(" */\n\n");
    std::printf("#ifndef UNIFRAC_WASM_PCOA_EXPECTED_H\n");
    std::printf("#define UNIFRAC_WASM_PCOA_EXPECTED_H\n\n");
    std::printf("static const unsigned int PCOA_EXPECTED_N      = %u;  /* n_samples */\n", N);
    std::printf("static const unsigned int PCOA_EXPECTED_K      = %u;  /* n_dims    */\n", K);
    std::printf("static const unsigned int PCOA_EXPECTED_SEED   = %u;\n\n", SEED);
    emit_array_double("PCOA_EXPECTED_EIGENVALUES",          eigenvalues,          K);
    emit_array_double("PCOA_EXPECTED_SAMPLES",              samples,              K * N);
    emit_array_double("PCOA_EXPECTED_PROPORTION_EXPLAINED", proportion_explained, K);
    std::printf("#endif /* UNIFRAC_WASM_PCOA_EXPECTED_H */\n");

    return 0;
}
