/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native ground-truth generator for
 * src/tests/wasm/test_unifrac_e2e_wasm.cpp.
 *
 * Computes the 6x6 UniFrac distance matrix for each supported method
 * on the synthetic fixture. Built natively against unifrac-binaries'
 * own in-memory subset (libssu inmem-only build) plus skbb-build's
 * libskbb.so. The unifrac TUs are compiled with -DUNIFRAC_WASM=1 so
 * the file-based paths are gated out; this keeps the generator
 * HDF5/lz4-free.
 *
 * Build & run via the wasm_regen_unifrac_expected Makefile target.
 */

#include "tests/wasm/fixtures.hpp"
#include "api.hpp"

#include <cstdlib>

struct MethodCase {
    const char* label;
    const char* method_arg;
};

static const MethodCase METHODS[] = {
    {"UNWEIGHTED",            "unweighted_fp64"},
    {"WEIGHTED_NORMALIZED",   "weighted_normalized_fp64"},
    {"WEIGHTED_UNNORMALIZED", "weighted_unnormalized_fp64"},
    {"GENERALIZED",           "generalized_fp64"},
};

static void emit_method(const MethodCase &mc) {
    const support_biom_t   table = {(char**) FIXTURE_OBS_IDS, (char**) FIXTURE_SAMP_IDS,
                                    (uint32_t*) FIXTURE_INDICES, (uint32_t*) FIXTURE_INDPTR,
                                    (double*) FIXTURE_DATA, FIXTURE_N_OBS, FIXTURE_N_SAMP, 0};
    const support_bptree_t tree  = {(bool*) FIXTURE_STRUCTURE, (double*) FIXTURE_LENGTHS,
                                    (char**) FIXTURE_NAMES, (int) FIXTURE_NPARENS};

    mat_full_fp64_t* result = nullptr;
    ComputeStatus status = one_off_matrix_inmem_v3(
        &table, &tree, mc.method_arg,
        false, 1.0, false, true, 1, 0, false, NULL, &result);
    if (status != okay || result == NULL) {
        std::fprintf(stderr, "FAIL: %s -> status %d\n", mc.label, (int) status);
        std::exit(1);
    }

    char buf[64];
    std::snprintf(buf, sizeof buf, "UNIFRAC_EXPECTED_%s", mc.label);
    emit_array_double(buf, result->matrix, FIXTURE_N_SAMP * FIXTURE_N_SAMP);

    destroy_mat_full_fp64(&result);
}

int main(void) {
    std::printf("/* AUTO-GENERATED by src/tests/wasm/generate_unifrac_expected.cpp.\n");
    std::printf(" * Do not hand-edit. Run `make wasm_regen_unifrac_expected` to refresh.\n");
    std::printf(" *\n");
    std::printf(" * Synthetic fixture (FIXTURE_OBS_IDS + FIXTURE_DATA + FIXTURE_STRUCTURE\n");
    std::printf(" * with all branch lengths = 1.0, see src/tests/wasm/fixtures.hpp).\n");
    std::printf(" * Generator runs natively against an in-memory-only build of libssu\n");
    std::printf(" * (-DUNIFRAC_WASM=1) linked against skbb-build's libskbb.so.\n");
    std::printf(" */\n\n");
    std::printf("#ifndef UNIFRAC_WASM_UNIFRAC_EXPECTED_H\n");
    std::printf("#define UNIFRAC_WASM_UNIFRAC_EXPECTED_H\n\n");
    std::printf("static const unsigned int UNIFRAC_EXPECTED_N = %d;\n\n", FIXTURE_N_SAMP);

    for (const auto &mc : METHODS) {
        emit_method(mc);
    }

    std::printf("#endif /* UNIFRAC_WASM_UNIFRAC_EXPECTED_H */\n");
    return 0;
}
