/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2016-2026, UniFrac development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * End-to-end WASM correctness test.
 *
 * Runs one_off_matrix_inmem_v3 under WASM for each in-scope UniFrac
 * method and compares the resulting 6x6 distance matrix to the
 * corresponding native oracle in
 *   src/tests/wasm/expected/unifrac_expected.h.
 *
 * Tolerance: 1e-5 absolute, matching src/testdata/validation_tests.sh.
 *
 * The native oracle is generated by
 *   src/tests/wasm/generate_unifrac_expected.cpp
 * which compiles the same unifrac source files NATIVELY with
 * -DUNIFRAC_WASM=1 + skbb-build's libskbb.so. Both paths therefore
 * exercise identical unifrac source through different toolchains.
 */

#include "tests/wasm/check_macros.hpp"
#include "tests/wasm/fixtures.hpp"
#include "tests/wasm/expected/unifrac_expected.h"
#include "api.hpp"

struct MethodCase {
    const char* label;
    const char* method_arg;
    const double* expected;
};

static const MethodCase METHODS[] = {
    {"unweighted",            "unweighted_fp64",            UNIFRAC_EXPECTED_UNWEIGHTED},
    {"weighted_normalized",   "weighted_normalized_fp64",   UNIFRAC_EXPECTED_WEIGHTED_NORMALIZED},
    {"weighted_unnormalized", "weighted_unnormalized_fp64", UNIFRAC_EXPECTED_WEIGHTED_UNNORMALIZED},
    {"generalized",           "generalized_fp64",           UNIFRAC_EXPECTED_GENERALIZED},
};

static void compare_method(const MethodCase &mc) {
    const support_biom_t   table = {(char**) FIXTURE_OBS_IDS, (char**) FIXTURE_SAMP_IDS,
                                    (uint32_t*) FIXTURE_INDICES, (uint32_t*) FIXTURE_INDPTR,
                                    (double*) FIXTURE_DATA, FIXTURE_N_OBS, FIXTURE_N_SAMP, 0};
    const support_bptree_t tree  = {(bool*) FIXTURE_STRUCTURE, (double*) FIXTURE_LENGTHS,
                                    (char**) FIXTURE_NAMES, (int) FIXTURE_NPARENS};

    mat_full_fp64_t* result = nullptr;
    ComputeStatus status = one_off_matrix_inmem_v3(
        &table, &tree, mc.method_arg,
        /*variance_adjust*/ false, /*alpha*/ 1.0,
        /*bypass_tips*/ false, /*normalize_sample_counts*/ true,
        /*n_substeps*/ 1,
        /*subsample_depth*/ 0, /*subsample_with_replacement*/ false,
        /*mmap_dir*/ NULL,
        &result);

    CHECK(status == okay);
    CHECK(result != nullptr);
    CHECK_EQ(result->n_samples, UNIFRAC_EXPECTED_N);

    const unsigned int total = FIXTURE_N_SAMP * FIXTURE_N_SAMP;
    for (unsigned int i = 0; i < total; i++) {
        if (!almost_equal<double>(result->matrix[i], mc.expected[i], 1e-5)) {
            std::fprintf(stderr,
                "FAIL %s entry [%u/%u] = %.10g; expected %.10g\n",
                mc.label, i / FIXTURE_N_SAMP, i % FIXTURE_N_SAMP,
                result->matrix[i], mc.expected[i]);
            std::exit(1);
        }
    }

    destroy_mat_full_fp64(&result);
    std::fprintf(stdout, "  %-22s OK\n", mc.label);
}

int main(void) {
    CHECK_EQ(UNIFRAC_EXPECTED_N, 6u);

    for (const auto &mc : METHODS) {
        compare_method(mc);
    }

    std::fprintf(stdout, "OK test_unifrac_e2e_wasm\n");
    return 0;
}
