/*
 * Expected Faith's PD values for the synthetic 5-OTU / 6-sample fixture
 * defined in src/tests/wasm/test_faith_pd_wasm.cpp.
 *
 * Provenance — derived BY HAND from:
 *   - The tree topology committed in test/capi_inmem_test.c:35-42
 *     (a multifurcating tree: root has three children — GG_OTU_1, an
 *     inner clade {GG_OTU_2, GG_OTU_3}, and an inner clade
 *     {GG_OTU_5, GG_OTU_4}).
 *   - All branch lengths set to 1.0 (the existing capi_inmem_test fixture
 *     uses zero lengths, which produces all-zero Faith's PD; we override
 *     to 1.0 here so the test exercises non-trivial path summation).
 *   - The CSR-encoded table in test/capi_inmem_test.c:25-27, whose
 *     correctness is guaranteed by the existing native CI pass on the
 *     unweighted-UniFrac matrix in capi_inmem_test.c:99-104.
 *
 * Faith's PD per sample = sum of branch lengths in the minimal subtree
 * connecting all observed tips (rooted; root has no incoming edge).
 *
 * Per-sample observed OTU sets (decoded from indices/indptr):
 *   Sample 0: {GG_OTU_2, GG_OTU_4}                           → PD = 4
 *   Sample 1: {GG_OTU_2, GG_OTU_4, GG_OTU_5}                 → PD = 5
 *   Sample 2: {GG_OTU_1, GG_OTU_3, GG_OTU_4, GG_OTU_5}       → PD = 6
 *   Sample 3: {GG_OTU_2, GG_OTU_3}                           → PD = 3
 *   Sample 4: {GG_OTU_2}                                     → PD = 2
 *   Sample 5: {GG_OTU_2, GG_OTU_3, GG_OTU_4}                 → PD = 5
 *
 * Stage 7 (end-to-end UniFrac) will additionally validate against
 * test500.biom oracle files generated by an unmodified native
 * libssu.so build, providing a real-data cross-check.
 */

#ifndef UNIFRAC_WASM_FAITH_PD_EXPECTED_H
#define UNIFRAC_WASM_FAITH_PD_EXPECTED_H

static const unsigned int FAITH_PD_EXPECTED_N = 6;

static const double FAITH_PD_EXPECTED[FAITH_PD_EXPECTED_N] = {
    4.0, 5.0, 6.0, 3.0, 2.0, 5.0
};

#endif /* UNIFRAC_WASM_FAITH_PD_EXPECTED_H */
