/* AUTO-GENERATED by src/tests/wasm/generate_pcoa_expected.cpp.
 * Do not hand-edit. Run `make wasm_regen_pcoa_expected` to refresh.
 *
 * Input: 6x6 unweighted-UniFrac distance matrix from
 *   test/capi_inmem_test.c:99-104 (native-CI-validated).
 * Seed: 42; n_eighs=3; produced via skbb_pcoa_fsvd_fp64
 * with su::set_random_seed-compatible seed transform.
 */

#ifndef UNIFRAC_WASM_PCOA_EXPECTED_H
#define UNIFRAC_WASM_PCOA_EXPECTED_H

static const unsigned int PCOA_EXPECTED_N      = 6;  /* n_samples */
static const unsigned int PCOA_EXPECTED_K      = 3;  /* n_dims    */
static const unsigned int PCOA_EXPECTED_SEED   = 42;

static const double PCOA_EXPECTED_EIGENVALUES[3] = {
    0x1.e40d390f253b8p-2,
    0x1.93f6f95309a4fp-3,
    0x1.2f08984b23fd3p-4
};

static const double PCOA_EXPECTED_SAMPLES[18] = {
    0x1.d667df5d4e57bp-5,
    -0x1.cab7ab94dbe5cp-3,
    0x1.8cf8d2d9ee63fp-4,
    0x1.8a206ebec04b9p-3,
    -0x1.7764320f7177p-3,
    -0x1.33562b507108p-4,
    0x1.92ec0bfe30b1ap-2,
    0x1.99818faa9fac7p-3,
    -0x1.d077d155f7145p-4,
    -0x1.42305ec9d441cp-2,
    0x1.f4be0b850bbeap-3,
    0x1.0b15d7e484af4p-5,
    -0x1.a7d07d5dc33bep-2,
    -0x1.96b90676b3708p-4,
    -0x1.e20f8ac45f138p-4,
    0x1.5cde7379736cbp-4,
    0x1.fce316bfeea8cp-5,
    0x1.69ace44f4b3a1p-3
};

static const double PCOA_EXPECTED_PROPORTION_EXPLAINED[3] = {
    0x1.5bc8e2e653ebdp-1,
    0x1.223e4aa0430afp-2,
    0x1.b37383fccb753p-4
};

#endif /* UNIFRAC_WASM_PCOA_EXPECTED_H */
