/* AUTO-GENERATED by src/tests/wasm/generate_permanova_expected.cpp.
 * Do not hand-edit. Run `make wasm_regen_permanova_expected` to refresh.
 *
 * Input: 6x6 unweighted-UniFrac distance matrix from
 *   test/capi_inmem_test.c:99-104 (native-CI-validated).
 * Grouping: {0,0,1,1,1,0}; n_perm=999; seed=42
 * Produced via skbb_permanova_fp64 with the
 * su::set_random_seed-compatible seed transform.
 */

#ifndef UNIFRAC_WASM_PERMANOVA_EXPECTED_H
#define UNIFRAC_WASM_PERMANOVA_EXPECTED_H

static const unsigned int PERMANOVA_EXPECTED_N      = 6;
static const unsigned int PERMANOVA_EXPECTED_N_PERM = 999;
static const unsigned int PERMANOVA_EXPECTED_SEED   = 42;

static const double PERMANOVA_EXPECTED_FSTAT  = 0x1.65cf675b385cdp+0;
static const double PERMANOVA_EXPECTED_PVALUE = 0x1.05a1cac083127p-1;

#endif /* UNIFRAC_WASM_PERMANOVA_EXPECTED_H */
